# Generated by Django 4.2 on 2023-09-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(default='My New Room', max_length=500),
        ),
    ]
